// THESE CANNOT BE REWRITTEN
// https://github.com/microsoft/coyote/issues/336
// "Bunit.Web.dll",
// "Microsoft.AspNetCore.Components.dll",
// "Microsoft.Extensions.Primitives.dll",
// "Microsoft.Extensions.Logging.dll",
// "Serilog.dll",
// "System.CommandLine.dll",
// "System.IO.Pipelines.dll",
// "System.Security.Cryptography.Pkcs.dll",
// "System.Security.Cryptography.Xml.dll",

//"AngleSharp.Css.dll",
//"AngleSharp.Diffing.dll",
//"AngleSharp.dll",
//"AngleSharpWrappers.dll",
//"AutoFixture.dll",
//"AutoFixture.Xunit2.dll",
//"Bunit.Core.dll",
//"bunit.coyotetest.dll",
//"Bunit.TestAssets.dll",
//"Bunit.Web.dll",
//"Castle.Core.dll",
//"coyote.dll",
//"CoyoteCoverageReportMerger.dll",
//"DiffEngine.dll",
//"EmptyFiles.dll",
//"Fare.dll",
//"Microsoft.ApplicationInsights.dll",
//"Microsoft.AspNetCore.Authorization.dll",
//"Microsoft.AspNetCore.Components.Authorization.dll",
//"Microsoft.AspNetCore.Components.dll",
//"Microsoft.AspNetCore.Components.Forms.dll",
//"Microsoft.AspNetCore.Components.Web.dll",
//"Microsoft.AspNetCore.Components.WebAssembly.Authentication.dll",
//"Microsoft.AspNetCore.Http.Abstractions.dll",
//"Microsoft.AspNetCore.Http.Features.dll",
//"Microsoft.AspNetCore.Metadata.dll",
//"Microsoft.Coyote.dll",
//"Microsoft.Coyote.Test.dll",
//"Microsoft.Extensions.DependencyInjection.Abstractions.dll",
//"Microsoft.Extensions.DependencyInjection.dll",
//"Microsoft.Extensions.DependencyModel.dll",
//"Microsoft.Extensions.Localization.Abstractions.dll",
//"Microsoft.Extensions.Logging.Abstractions.dll",
//"Microsoft.Extensions.Logging.dll",
//"Microsoft.Extensions.Options.dll",
//"Microsoft.Extensions.Primitives.dll",
//"Microsoft.JSInterop.dll",
//"Microsoft.TestPlatform.CommunicationUtilities.dll",
//"Microsoft.TestPlatform.CoreUtilities.dll",
//"Microsoft.TestPlatform.CrossPlatEngine.dll",
//"Microsoft.TestPlatform.PlatformAbstractions.dll",
//"Microsoft.TestPlatform.Utilities.dll",
//"Microsoft.VisualStudio.CodeCoverage.Shim.dll",
//"Microsoft.VisualStudio.TestPlatform.Common.dll",
//"Microsoft.VisualStudio.TestPlatform.ObjectModel.dll",
//"Microsoft.Win32.Registry.AccessControl.dll",
//"Microsoft.Win32.SystemEvents.dll",
//"Mono.Cecil.dll",
//"Mono.Cecil.Mdb.dll",
//"Mono.Cecil.Pdb.dll",
//"Mono.Cecil.Rocks.dll",
//"Moq.dll",
//"Newtonsoft.Json.dll",
//"NuGet.Frameworks.dll",
//"Serilog.dll",
//"Serilog.Extensions.Logging.dll",
//"Shouldly.dll",
//"System.CodeDom.dll",
//"System.CommandLine.dll",
//"System.ComponentModel.Composition.dll",
//"System.ComponentModel.Composition.Registration.dll",
//"System.Configuration.ConfigurationManager.dll",
//"System.Data.Odbc.dll",
//"System.Data.OleDb.dll",
//"System.Data.SqlClient.dll",
//"System.Diagnostics.EventLog.dll",
//"System.Diagnostics.PerformanceCounter.dll",
//"System.DirectoryServices.AccountManagement.dll",
//"System.DirectoryServices.dll",
//"System.DirectoryServices.Protocols.dll",
//"System.Drawing.Common.dll",
//"System.IO.Packaging.dll",
//"System.IO.Pipelines.dll",
//"System.IO.Ports.dll",
//"System.Management.dll",
//"System.Private.ServiceModel.dll",
//"System.Reflection.Context.dll",
//"System.Runtime.Caching.dll",
//"System.Security.Cryptography.Pkcs.dll",
//"System.Security.Cryptography.ProtectedData.dll",
//"System.Security.Cryptography.Xml.dll",
//"System.Security.Permissions.dll",
//"System.ServiceModel.dll",
//"System.ServiceModel.Duplex.dll",
//"System.ServiceModel.Http.dll",
//"System.ServiceModel.NetTcp.dll",
//"System.ServiceModel.Primitives.dll",
//"System.ServiceModel.Security.dll",
//"System.ServiceModel.Syndication.dll",
//"System.ServiceProcess.ServiceController.dll",
//"System.Threading.AccessControl.dll",
//"System.Windows.Extensions.dll",
//"testhost.dll",
//"xunit.abstractions.dll",
//"xunit.assert.dll",
//"Xunit.Combinatorial.dll",
//"xunit.core.dll",
//"xunit.execution.dotnet.dll",
//"xunit.runner.reporters.netcoreapp10.dll",
//"xunit.runner.utility.netcoreapp10.dll",
//"xunit.runner.visualstudio.dotnetcore.testadapter.dll",
